# Site settings
title: ZhangNian Blog
SEOTitle: 张念的博客 | Hux Blog
header-img: img/home-bg.jpg
email: zhanghenshui945@gmail.com
description: "关于程序与设计、黑客与画家 | 黄玄，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界。"
